
package beer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BeerService", targetNamespace = "http://server/", wsdlLocation = "http://simon.ist.rit.edu:8080/beer/BeerService?wsdl")
public class BeerService
    extends Service
{

    private final static URL BEERSERVICE_WSDL_LOCATION;
    private final static WebServiceException BEERSERVICE_EXCEPTION;
    private final static QName BEERSERVICE_QNAME = new QName("http://server/", "BeerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://simon.ist.rit.edu:8080/beer/BeerService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BEERSERVICE_WSDL_LOCATION = url;
        BEERSERVICE_EXCEPTION = e;
    }

    public BeerService() {
        super(__getWsdlLocation(), BEERSERVICE_QNAME);
    }

    public BeerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BEERSERVICE_QNAME, features);
    }

    public BeerService(URL wsdlLocation) {
        super(wsdlLocation, BEERSERVICE_QNAME);
    }

    public BeerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BEERSERVICE_QNAME, features);
    }

    public BeerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BeerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Beer
     */
    @WebEndpoint(name = "BeerPort")
    public Beer getBeerPort() {
        return super.getPort(new QName("http://server/", "BeerPort"), Beer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Beer
     */
    @WebEndpoint(name = "BeerPort")
    public Beer getBeerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "BeerPort"), Beer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BEERSERVICE_EXCEPTION!= null) {
            throw BEERSERVICE_EXCEPTION;
        }
        return BEERSERVICE_WSDL_LOCATION;
    }

}
